development:
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ervevan_events
  username: androdb
  password: andro1111
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000