development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: development

production:
  adapter: postgresql
  database: erevan_events
  username: rails
  password: dAgZvKDtGA
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
